### ISSUE TITLE
[Question] How to build skia viewer?

### ISSUE THREAD

**Issue by KnIfER** [JetBrains/skia-build#6]
https://skia.org/docs/user/sample/viewer/ : 
> The Viewer can be built using the regular GN build process, e.g.
> 
> ```
> bin/gn gen out/Release --args='is_debug=false'
> ninja -C out/Release viewer
> ```

But ...

```
ninja: error: unknown target 'viewer'
Traceback (most recent call last):
  File "script/build.py", line 79, in <module>
  File "script/build.py", line 74, in main
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['..\\depot_tools\\ninja.exe', '-C', 'out\\Release-x64', 'skia', 'modules', 'viewer']' returned non-zero exit status 1.
Error: Process completed with exit code 1.
```

**Comment by tonsky** [comment]
Sorry, I haven’t looked into it. Try asking here https://groups.google.com/g/skia-discuss?pli=1 ?

**Comment by KnIfER** [comment]
Should use `bin/gn gen out/Release --args='is_debug=false'` to configure the build

**Comment by KnIfER** [comment]
Or add `skia_enable_tools=true`
