### ISSUE TITLE
HEIC support (libheif)

### ISSUE THREAD

**Issue by werthdavid** [JetBrains/skia-build#7]
Hey guys, 
great work, thanks for that repo! I'm currently trying to create my own version of Skija (Java), especially the HEIC support is interesting for me. I managed to build skia with this repo and skija with your other build scripts. Now I wanted to enable HEIC support but I can't figure out how to achieve that... is there any chance this will be supported be this project or can you give me a hint what I could try?

Cheers,
David

**Comment by tonsky** [comment]
I don’t think Skia includes it https://github.com/JetBrains/skija/issues/90#issuecomment-796296812. You are probably better off with using a library for that

**Comment by werthdavid** [comment]
thanks for the fast reply. Unfortunately I have not found a working library in Java for that. I thought Skia does have support for HEIC, it just has to be enabled..

**Comment by tonsky** [comment]
On Android, it relies on Android implementation. Everywhere else, I guess it just doesn’t support it :)

**Comment by werthdavid** [comment]
Oh, I see, in https://bugs.chromium.org/p/skia/issues/detail?id=11733 Google is very clear about this. I looked into Skia a little bit and thought the libheif comments meant that it does rely on that library in non-android platforms. Thanks for the clarification!
